@subdominio = render-examen-2


###
# 1: Mostrar su código IDAT y su nombre en el siguiente formato: CÓDIGO - NOMBRE
GET https://{{subdominio}}.onrender.com/

###
# 2: Mostrar su código IDAT
GET https://{{subdominio}}.onrender.com/idat/codigo

###
# 3: Mostrar su nombre completo
GET https://{{subdominio}}.onrender.com/idat/nombre-completo